import Head from "next/head";


const HeadsBase = () => {
  return (
    <Head>
      <title>T3 Twitter Clone</title>
      <meta name="description" content="Twitter Clone generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadsBase