import { useUser, SignUp, SignOutButton, SignInButton } from "@clerk/nextjs";
import Head from "next/head";
import MainComponent from "./components/MainComponent";

export default function Home() {
  const user = useUser();  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="border-x w-full md:max-w-2xl border-slate-50 h-full">
          { user ? <SignOutButton /> : <SignInButton /> }
          <SignUp />
          <MainComponent />
        </div>
      </main>
    </>
  );
}
